

- name: uninstall conflicting docker packages 
  apt: 
    name: 
      - docker.io
      - docker-doc 
      - docker-compose
      - docker-compose-v2 
      - podman-docker 
      - containerd 
      - runc
    state: absent

- name: install docker pre-requisits
  apt: 
    update_cache: true
    name: 
      - ca-certificates
      - curl 
      - gnupg
    state: present 

- name: create direcotry for docker keyrings 
  file: 
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: 0755
    state: directory 

- name: download docker gpg key 
  get_url: 
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0444

- name: get system architecture 
  shell: dpkg --print-architecture
  register: arch
  changed_when: false 

- name: add docker apt repository 
  apt_repository: 
    repo: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present 

- name: install docker official packages 
  apt: 
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
    update_cache: true 

- name: run hello world container 
  docker_container: 
    name: hello
    image: hello-world
    state: started 

